# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(default='description')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('img', models.ImageField(height_field='height', upload_to=b'', width_field='width')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
